// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Render from "./lib/Render.bs.js";

function App(Props) {
  return React.createElement("h1", undefined, Render.s("My app"));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
