// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var container = document.querySelector("#root");

if (container == null) {
  console.log("#root tag not found on html!");
} else {
  ReactDom.render(React.createElement(App.make, {}), container);
}

export {
  
}
/* container Not a pure module */
